-- ============================================================
-- VIEW: ORDER REVENUE
-- ============================================================
--
-- Calculates the realized revenue for each sales order after
-- applying line-item discounts.
--
-- Result grain:
--     One row per sales order.
--
-- Revenue calculation:
--     quantity × unit_price × (1 - discount%)
--
-- DESIGN DECISION:
-- Revenue is calculated at order level first so downstream
-- analytics can reuse the same definition without repeatedly
-- aggregating individual sales-order items.
--
-- Cancelled orders are retained here intentionally. Downstream
-- reporting views decide whether cancelled orders should be
-- included for their specific business metric.
-- ============================================================

CREATE VIEW v_order_revenue AS

SELECT so.so_id, so.customer_id, so.warehouse_id, so.employee_id, so.order_date, so.status,

       SUM(soi.quantity * soi.unit_price * (1 - soi.discount_pct/100.0)) AS order_total

FROM sales_orders so

JOIN sales_order_items soi ON soi.so_id = so.so_id

GROUP BY so.so_id, so.customer_id, so.warehouse_id, so.employee_id, so.order_date, so.status;


-- ============================================================
-- VIEW: CUSTOMER LIFETIME VALUE
-- ============================================================
--
-- Aggregates customer-level revenue and order activity from the
-- reusable order-revenue view.
--
-- Result grain:
--     One row per customer with at least one non-cancelled order.
--
-- lifetime_value:
--     Total revenue generated by the customer.
--
-- order_count:
--     Number of non-cancelled orders placed by the customer.
--
-- DESIGN DECISION:
-- Building this on top of v_order_revenue keeps the revenue
-- calculation centralized and avoids duplicating line-item
-- discount logic.
-- ============================================================

CREATE VIEW v_customer_ltv AS

SELECT c.customer_id, c.name, c.segment,

       SUM(orv.order_total) AS lifetime_value,

       COUNT(orv.so_id) AS order_count

FROM customers c

JOIN v_order_revenue orv ON orv.customer_id = c.customer_id AND orv.status != 'cancelled'

GROUP BY c.customer_id, c.name, c.segment;


-- ============================================================
-- VIEW: DAILY REVENUE
-- ============================================================
--
-- Aggregates order-level revenue into a daily reporting grain.
--
-- Result grain:
--     One row per date containing at least one non-cancelled order.
--
-- DESIGN DECISION:
-- This provides a reusable intermediate layer for time-series
-- analytics such as moving averages, monthly aggregation, and
-- rolling-period revenue calculations.
--
-- Cancelled orders are excluded so the resulting metric represents
-- recognized project revenue rather than gross order activity.
-- ============================================================

CREATE VIEW v_daily_revenue AS

SELECT order_date, SUM(order_total) AS revenue

FROM v_order_revenue

WHERE status != 'cancelled'

GROUP BY order_date;