-- ============================================================
-- 26. Top 20 Customers by Lifetime Value
-- ============================================================
--
-- Calculates cumulative revenue generated by each customer from
-- all non-cancelled sales orders.
--
-- c   = customers
-- so  = sales_orders
-- soi = sales_order_items
--
-- Lifetime value is based on transaction-level selling price after
-- discounts:
--     quantity × unit_price × (1 - discount%)
--
-- Result grain: one row per customer.
--
-- LIMIT 20 identifies the highest-value customers by historical
-- revenue contribution.
-- ============================================================

SELECT c.name, SUM(soi.quantity * soi.unit_price * (1 - soi.discount_pct/100.0)) AS lifetime_value

FROM customers c

JOIN sales_orders so
    ON so.customer_id = c.customer_id
    AND so.status != 'cancelled'

JOIN sales_order_items soi
    ON soi.so_id = so.so_id

GROUP BY c.name
ORDER BY lifetime_value DESC
LIMIT 20;


-- ============================================================
-- 27. Customer Segment Revenue Share
-- ============================================================
--
-- Compares revenue generated by each customer segment and its
-- percentage contribution to total non-cancelled revenue.
--
-- c   = customers
-- so  = sales_orders
-- soi = sales_order_items
--
-- The outer window SUM provides the global revenue denominator,
-- while the grouped SUM provides the segment-level numerator.
--
-- Result grain: one row per customer segment.
--
-- Because cancelled orders are excluded from the underlying
-- aggregation, the percentage shares sum to 100% across the
-- returned segments.
-- ============================================================

SELECT c.segment, SUM(soi.quantity * soi.unit_price * (1 - soi.discount_pct/100.0)) AS revenue,

       ROUND(100.0 * SUM(soi.quantity * soi.unit_price * (1 - soi.discount_pct/100.0))
             / SUM(SUM(soi.quantity * soi.unit_price * (1 - soi.discount_pct/100.0))) OVER (), 2) AS pct

FROM customers c

JOIN sales_orders so
    ON so.customer_id = c.customer_id
    AND so.status != 'cancelled'

JOIN sales_order_items soi
    ON soi.so_id = so.so_id

GROUP BY c.segment
ORDER BY revenue DESC;


-- ============================================================
-- 28. Customers with No Orders in the Last 6 Months
-- ============================================================
--
-- Identifies customers with no sales order activity during the
-- last six months.
--
-- NOT EXISTS is used to test for the absence of a qualifying
-- order for each customer.
--
-- The correlation:
--     so.customer_id = c.customer_id
--
-- ensures the six-month activity check is performed independently
-- for each customer.
--
-- Cancelled orders are intentionally not excluded here because
-- the query is measuring order activity rather than realized
-- revenue.
--
-- Result grain: one row per customer with no recent order.
--
-- BUSINESS NOTE:
-- This is a simple inactivity-based churn-risk indicator. It does
-- not account for customer purchase cycles, segment, contract
-- terms, or expected reorder frequency.
-- ============================================================

SELECT c.customer_id, c.name

FROM customers c

WHERE NOT EXISTS (

    SELECT 1
    FROM sales_orders so

    WHERE so.customer_id = c.customer_id
      AND so.order_date > now() - interval '6 months'

)

LIMIT 50;


-- ============================================================
-- 29. Customer Order Frequency Distribution
-- ============================================================
--
-- Groups customers into order-frequency buckets to show how the
-- customer base is distributed by historical order count.
--
-- The inner query first establishes one row per customer and
-- assigns the appropriate order-count bucket.
--
-- LEFT JOIN is important here because customers with zero orders
-- must also appear in the distribution.
--
-- Buckets:
--     0
--     1-3
--     4-10
--     10+
--
-- Result grain:
--     outer query -> one row per order-count bucket
--     inner query -> one row per customer
--
-- BUSINESS NOTE:
-- The distribution provides a quick view of customer engagement
-- and the proportion of inactive or repeat customers.
-- ============================================================

SELECT order_count_bucket, COUNT(*) AS num_customers

FROM (

    SELECT c.customer_id,

           CASE
               WHEN COUNT(so.so_id) = 0 THEN '0'
               WHEN COUNT(so.so_id) BETWEEN 1 AND 3 THEN '1-3'
               WHEN COUNT(so.so_id) BETWEEN 4 AND 10 THEN '4-10'
               ELSE '10+'
           END AS order_count_bucket

    FROM customers c

    LEFT JOIN sales_orders so
        ON so.customer_id = c.customer_id

    GROUP BY c.customer_id

) t

GROUP BY order_count_bucket
ORDER BY order_count_bucket;


-- ============================================================
-- 30. RFM-Style Customer Metrics
-- ============================================================
--
-- Builds three customer-level metrics commonly used for
-- customer segmentation:
--
-- Recency:
--     Days since the customer's most recent non-cancelled order.
--
-- Frequency:
--     Number of distinct non-cancelled sales orders.
--
-- Monetary:
--     Total revenue generated after discounts.
--
-- c   = customers
-- so  = sales_orders
-- soi = sales_order_items
--
-- Result grain: one row per customer with at least one
-- non-cancelled order.
--
-- BUSINESS NOTE:
-- This is RFM-style rather than a complete RFM scoring model.
-- The query calculates the three raw metrics but does not assign
-- customer scores or segments.
--
-- LIMIT 50 returns a sample of the resulting customer-level
-- metrics; without an ORDER BY, these are not specifically the
-- top 50 customers by any RFM metric.
-- ============================================================

SELECT c.customer_id, c.name,

       now()::date - MAX(so.order_date) AS recency_days,

       COUNT(DISTINCT so.so_id) AS frequency,

       SUM(soi.quantity * soi.unit_price * (1 - soi.discount_pct/100.0)) AS monetary

FROM customers c

JOIN sales_orders so
    ON so.customer_id = c.customer_id
    AND so.status != 'cancelled'

JOIN sales_order_items soi
    ON soi.so_id = so.so_id

GROUP BY c.customer_id, c.name

LIMIT 50;